### ISSUE TITLE
How do I connect to iOS 13 phone

### ISSUE THREAD

**Issue by AtomicVein** [neoneggplant/EggShell#125]
How would I connect to my phone, I’m jailbroken. Not sure what to put in my terminal on my phone.

**Comment by danielcunn123** [comment]
Works fine on IOS 13.2.3 (Checkra1n Jailbreak)

`echo '[PAYLOAD_DATA]' > payload.sh`
`chmod u+x`
`./payload.sh`

Then execute EggShell multi-handler or NetCat from ATTACKER machine to listen for connections.

**Comment by AtomicVein** [comment]
> Works fine on IOS 13.2.1
> 
> `echo [PAYLOAD_DATA] > payload.sh`
> `chmod u+x`
> `./payload.sh`
> 
> Then execute EggShell multi-handler or NetCat from ATTACKER machine to listen for connections.

This didn't seem to work for me. could you fill in {payload data with an example of how you put it in, and chmod u+x says its an invalid command and i need something after u+x

**Comment by vintendpower** [comment]
Would love to Look more into this and offer what help I can. I was messing with it today for ios 12.0.1 and I had a hard time installing it Cause Silo (Iphone max xs here with Chimera) Was having issues installing it due to Depends. 

So you are saying you are able to get this working on ios 13 as well? Do most of the features still work? mic and so on  ?

**Comment by danielcunn123** [comment]
> This didn't seem to work for me. could you fill in {payload data with an example of how you put it in, and chmod u+x says its an invalid command and i need something after u+x

@AtomicVein hopefully this issue is resolved after we made contact via email.
If so, please close this issue.


@vintendpower on a system running MacOS/Linux run the following:
`git clone https://github.com/neoneggplant/EggShell.git`
`cd EggShell`
`python eggshell.py`

Requirements to run on host should be Python2 - (Python3 wont work)


![EggShell_1](https://user-images.githubusercontent.com/44081787/70420426-97c2d480-1acc-11ea-94e8-5de239e5a100.PNG)
![EggShell_2](https://user-images.githubusercontent.com/44081787/70420431-98f40180-1acc-11ea-9593-4a767712145f.PNG)


My bad, I did not add ' ' to [PAYLOAD_DATA], will fix that now.
